import type { Artwork } from './artwork-service';

const mockArtworks: Artwork[] = [
  {
    id: 'p1',
    name: 'Blå Abstraktion',
    type: 'painting',
    dimensions: '100x80 cm',
    price: 7500,
    images: [{ url: 'https://picsum.photos/seed/p1/800/1000', dataAiHint: 'abstract painting' }],
    primaryImageIndex: 0,
    status: 'available',
    creationDate: '2023-05-15',
    materials: 'Akryl på lærred',
    description: 'En dyb og følelsesladet udforskning af blå nuancer, der skaber en følelse af ro og introspektion. Værket er bygget op af mange lag maling, hvilket giver en rig tekstur og dybde.',
    vatRate: 5,
  },
  {
    id: 'k1',
    name: 'Jordbunden Skål',
    type: 'keramik',
    dimensions: 'Ø 30 cm, H 15 cm',
    price: 2200,
    diameter: 30,
    height: 15,
    weight: 2.5,
    images: [{ url: 'https://picsum.photos/seed/k1/800/800', dataAiHint: 'ceramic bowl' }],
    primaryImageIndex: 0,
    status: 'available',
    creationDate: '2023-09-20',
    materials: 'Stentøj, reaktiv glasur',
    description: 'Hånddrejet stentøjsskål med en unik reaktiv glasur, der minder om et tørt, sprukket landskab. Perfekt som et centralt stykke på et bord.',
    vatRate: 25,
  },
  {
    id: 'w1',
    name: 'Metalsymfoni',
    type: 'vægkunst',
    dimensions: '120x60 cm',
    price: 11000,
    images: [{ url: 'https://picsum.photos/seed/w1/1200/600', dataAiHint: 'metal wall art' }],
    primaryImageIndex: 0,
    status: 'sold',
    creationDate: '2022-11-01',
    materials: 'Slebet stål og kobber',
    description: 'Et dynamisk stykke vægkunst skabt af slebet og formet metal. Lysets spil på overfladerne skaber en konstant foranderlig visuel oplevelse.',
    vatRate: 5,
  },
  {
    id: 'p2',
    name: 'Gylden Time',
    type: 'painting',
    dimensions: '120x100 cm',
    price: 9800,
    images: [
        { url: 'https://picsum.photos/seed/p2/1000/1200', dataAiHint: 'abstract landscape' },
        { url: 'https://picsum.photos/seed/p2-detail/800/800', dataAiHint: 'painting texture' }
    ],
    primaryImageIndex: 0,
    status: 'available',
    creationDate: '2024-01-10',
    materials: 'Olie og bladguld på lærred',
    description: 'Inspireret af det varme, gyldne lys lige før solnedgang. Bladguld er inkorporeret for at fange og reflektere lyset, hvilket giver værket en levende glød.',
    vatRate: 5,
  },
  {
    id: 'k2',
    name: 'Havets Vase',
    type: 'keramik',
    dimensions: 'H 45 cm',
    price: 3800,
    height: 45,
    images: [{ url: 'https://picsum.photos/seed/k2/800/1200', dataAiHint: 'ceramic vase' }],
    primaryImageIndex: 0,
    status: 'available',
    creationDate: '2023-02-28',
    materials: 'Porcelæn, krystalglasur',
    description: 'En høj, elegant vase i porcelæn med en krystalglasur i dybe blå og grønne toner, der minder om havets dyb. Hver krystalformation er unik.',
    vatRate: 25,
  },
  {
    id: 'p3',
    name: 'Byens Puls',
    type: 'painting',
    dimensions: '150x120 cm',
    price: 14500,
    images: [{ url: 'https://picsum.photos/seed/p3/1200/1500', dataAiHint: 'cityscape painting' }],
    primaryImageIndex: 0,
    status: 'sold',
    creationDate: '2023-08-05',
    materials: 'Mixed media på lærred',
    description: 'En energisk og abstrakt fortolkning af byens liv og bevægelse. Værket kombinerer maling, kul og avisudklip for at skabe en kompleks og lagdelt overflade.',
    vatRate: 5,
  },
];

export function getMockArtworks(): Artwork[] {
  return mockArtworks;
}
